# Generated by Django 2.2.4 on 2019-10-07 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Session'),
        ),
    ]
