# Generated by Django 2.2.4 on 2019-10-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20191007_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='confirm',
            field=models.BooleanField(default=True),
        ),
    ]
