# Generated by Django 2.2.4 on 2019-10-15 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_registration_confirm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': 'Wallet'},
        ),
        migrations.AlterField(
            model_name='item',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.Session'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='for_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Session', verbose_name='Session'),
        ),
    ]
