# Generated by Django 2.2.4 on 2019-10-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191007_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reg_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
